apiVersion: v1
kind: Pod
metadata:
  name: exampl-pod
  namespace: tools
  labels:
    k8s-label: awdawdwa
  annotations:
    jenkinsjoblabel: example-pod
spec:
  # affinity:
  #   podAntiAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #     - labelSelector:
  #         matchExpressions:
  #         - key: component
  #           operator: In
  #           values:
  #           - jenkins-jenkins-master
  #       topologyKey: "kubernetes.io/hostname"
  containers:
  - name: fuchicorptools
    image: fuchicorp/buildtools:latest
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    # volumeMounts:
    #   - mountPath: /var/run/docker.sock
    #     name: docker-sock
    #   - mountPath: /etc/secrets/service-account/
    #     name: google-service-account
  serviceAccountName: common-service-account
