apiVersion: v1
kind: Pod
metadata:
  name: pod-service-account-test
  labels:
    app: pod-service-account-test
spec:
  serviceAccountName: api-fsadykov
  automountServiceAccountToken: true
  containers:
  - name: kube-client-container
    image: fsadykov/kube-python-client:0.2
    args: ["--name=appone", "--namespace=default"]
