import hudson.EnvVars

def app
properties([
  parameters([
    booleanParam(defaultValue: false,
      description: 'Click this if you would like to deploy to latest',
      name: 'PUSH_LATEST'
      )])])

node {

  // Pooling the docker image
  checkout scm

  stage('Build docker image') {
    dir("${WORKSPACE}/kube-testing") {
      // Build the docker image
      app = docker.build("fsadykov/docker-testing")
      }
  }


  stage('Push image') {

     // Push docker image to the Docker hub
      docker.withRegistry('', 'dockerhub-credentials') {
          app.push("0.${BUILD_NUMBER}")

          // If push to latest parameters selected
          if (params.PUSH_LATEST){
            app.push("latest")
          }
      }
  }

  stage('Clean up') {
    sh """
    docker rmi --force python:latest
    docker rmi --force fsadykov/docker-testing:latest
    docker rmi --force fsadykov/docker-testing:0.${BUILD_NUMBER}
    """

  }
}
